repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pdm run test -m "not slow"
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pdm run test
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push, pre-merge-commit, pre-rebase]
